/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atk.view;

/**
 *
 * @author dicky-java
 */
public class PanelTambahBulanView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PanelTambahBulanView
     */
    public PanelTambahBulanView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLaporanTambah1 = new com.atk.panel.PanelLaporanTambah();
        jPanel1 = new javax.swing.JPanel();
        panelLaporanTambahSupplier1 = new com.atk.panel.PanelLaporanTambahSupplier();

        setClosable(true);
        setIconifiable(true);
        setTitle("Laporan Penambahan Barang");

        jTabbedPane1.addTab("Laporan Bulanan", panelLaporanTambah1);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelLaporanTambahSupplier1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Laporan Supplier", jPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.atk.panel.PanelLaporanTambah panelLaporanTambah1;
    private com.atk.panel.PanelLaporanTambahSupplier panelLaporanTambahSupplier1;
    // End of variables declaration//GEN-END:variables
}
