/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atk.view;

import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author dicky-java
 */
public class ReportView extends javax.swing.JInternalFrame {

    private JRViewer jrv;
    public ReportView(JRViewer jrv) {
        this.jrv=jrv;
        initComponents();
        panelLaporan.add(jrv, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaporan = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        panelLaporan.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelLaporan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelLaporan;
    // End of variables declaration//GEN-END:variables
}
