/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atk.dialog;
import com.atk.MenuUtama;
import com.atk.dao.PenggunaDao;
import com.atk.model.Pengguna;
import java.awt.Color;
import javax.swing.JOptionPane;
import usu.widget.Form;
/**
 *
 * @author dicky-java
 */
public class Login extends Form {

    private PenggunaDao dao=new PenggunaDao();
    private Pengguna pengguna;
    private MenuUtama mu;
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        mu=new MenuUtama();
        this.getRootPane().setDefaultButton(btn_masuk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new com.atk.swingmakeover.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        panelTransparan2 = new com.atk.swingmakeover.PanelTransparan();
        txt_username = new com.atk.swingmakeover.TextBoxPutih();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new com.atk.swingmakeover.PasswordPutih();
        panelTransparan1 = new com.atk.swingmakeover.PanelTransparan();
        btn_masuk = new com.atk.swingmakeover.ButtonPutih();
        btn_batal = new com.atk.swingmakeover.ButtonPutih();
        panelTransparan3 = new com.atk.swingmakeover.PanelTransparan();
        jLabel4 = new javax.swing.JLabel();

        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_TOP);
        setAnimationTime(2000);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atk/gambar/gembok.png"))); // NOI18N

        panelTransparan2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

        txt_username.setBackground(new Color(0f, 0f, 0f, 0f)
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password");

        txt_password.setBackground(new Color(0f, 0f, 0f, 0f)
        );

        javax.swing.GroupLayout panelTransparan2Layout = new javax.swing.GroupLayout(panelTransparan2);
        panelTransparan2.setLayout(panelTransparan2Layout);
        panelTransparan2Layout.setHorizontalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        panelTransparan2Layout.setVerticalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btn_masuk.setText("Masuk");
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        panelTransparan1.add(btn_masuk);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        panelTransparan1.add(btn_batal);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PT.KOTAMAS MAKMUR NATIONAL AGENCY");

        javax.swing.GroupLayout panelTransparan3Layout = new javax.swing.GroupLayout(panelTransparan3);
        panelTransparan3.setLayout(panelTransparan3Layout);
        panelTransparan3Layout.setHorizontalGroup(
            panelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan3Layout.setVerticalGroup(
            panelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(panelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(panelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(panelGradient1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
        dao=new PenggunaDao();
        String username = txt_username.getText();
        char[]pwd = txt_password.getPassword();
        String password=new String(pwd);
        if(username.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username masih kosong");
        }else if(password.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password masih kosong");
        }else{
            pengguna=dao.login(username, password);
        if(pengguna!=null){
            mu.setVisible(true);
            mu.getLbl_pengguna().setText(pengguna.getUsername());
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Username dan Password tidak valid");
            txt_username.setText("");
            txt_password.setText("");
        }
        }
        
    }//GEN-LAST:event_btn_masukActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.atk.swingmakeover.ButtonPutih btn_batal;
    private com.atk.swingmakeover.ButtonPutih btn_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.atk.swingmakeover.PanelGradient panelGradient1;
    private com.atk.swingmakeover.PanelTransparan panelTransparan1;
    private com.atk.swingmakeover.PanelTransparan panelTransparan2;
    private com.atk.swingmakeover.PanelTransparan panelTransparan3;
    private com.atk.swingmakeover.PasswordPutih txt_password;
    private com.atk.swingmakeover.TextBoxPutih txt_username;
    // End of variables declaration//GEN-END:variables
}
